spring:
  application:
    name: Gerenciador de senhas
  jpa:
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/senhas_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 
    password:
---
server:
  port: 8080
---
spring:
  profiles: development
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/senhas_dev
---
spring:
  profiles: test
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/senhas_tst
---
spring:
  profiles: production
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/senhas
